# Generated by Django 6.0.6 on 2026-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('replied', 'Replied'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
