# Generated by Django 6.0.6 on 2026-07-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='7wtfhZwyrcc', max_length=50, null=True),
        ),
    ]
