# Generated by Django 6.0.6 on 2026-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_storesetting_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sender_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
