# Generated by Django 6.0.6 on 2026-07-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_sender_number_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='bkash_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='nagad_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
