# Generated by Django 6.0.6 on 2026-07-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_1_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_2_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=500, upload_to='banners/'),
        ),
    ]
