# Generated by Django 6.0.6 on 2026-07-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_banner_button_1_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='instagram/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
